[package]
name = "rams"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "rams_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
str0m = "0.18.1"
tokio = { version = "1", features = ["full"], optional = true }
tokio-tungstenite = { version = "0.26", optional = true }
webrtc-media = "0.4"
futures-util = "0.3"

[features]
default = ["quick", "hybrid", "core"]
core = []
hybrid = ["core"]
quick = ["hybrid", "tokio", "tokio-tungstenite"]

[target."cfg(any(target_os = \"linux\", target_os = \"dragonfly\", target_os = \"freebsd\", target_os = \"openbsd\", target_os = \"netbsd\"))".dependencies]
webkit2gtk = { version = "2.0.2", features = ["v2_40"] }
